name:  Test and Publish

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup python env.
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Flake8
        run: |
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 --max-line-length=120

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run tests
        run: |
          cd src
          poetry run pytest --cov tests/

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        run: |
          ls
          pip install my_math*.whl

  build:
    runs-on: ubuntu-latest
    needs:
      - unit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Build Python package
        run: |
          poetry build
          ls dist/
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist
